apiVersion: v1
kind: ServiceAccount
metadata:
  name: cde-payment-sa
  namespace: payments-processing
  annotations:
    iam.gke.io/gcp-service-account: "cde-payment-workload@YOUR_PROJECT_ID.iam.gserviceaccount.com"
automountServiceAccountToken: true

# created by @jsaccomani
