apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: standard
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: wiz-sensor-egress
  namespace: wiz-agent
spec:
  podSelector:
    matchLabels:
      name: wiz-sensor
  policyTypes:
  - Egress
  egress:
  # Permit HTTPS outbound calls to registry.wiz.io
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
    ports:
    - protocol: TCP
      port: 443
  # Permit internal DNS resolution
  - to:
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53

# created by @jsaccomani
